### ISSUE TITLE
Deadlocks when using multiple consumers

### ISSUE THREAD

**Issue by cporte** [rabbitmq/rabbitmq-stream-java-client#49]
Hello,

While giving a try to the library we found a deadlock occurring when a consumer is started while another one (different name, different stream) is stopping.

Here is the relevant thread dump:

```
"rabbitmq-actors-dispatcher-33" - Thread t@89
   java.lang.Thread.State: BLOCKED
        at com.rabbitmq.stream.impl.ConsumersCoordinator$ManagerPool.maybeDisposeManager(ConsumersCoordinator.java:334)
        - waiting to lock <1db2727e> (a com.rabbitmq.stream.impl.ConsumersCoordinator$ManagerPool) owned by "oems-securities-akka.rabbitmq-actors-dispatcher-34" t@90
        at com.rabbitmq.stream.impl.ConsumersCoordinator$ManagerPool.access$1300(ConsumersCoordinator.java:293)
        at com.rabbitmq.stream.impl.ConsumersCoordinator$ClientSubscriptionsManager.remove(ConsumersCoordinator.java:716)
        - locked <78cd3cab> (a com.rabbitmq.stream.impl.ConsumersCoordinator$ClientSubscriptionsManager)
        at com.rabbitmq.stream.impl.ConsumersCoordinator$SubscriptionTracker.cancel(ConsumersCoordinator.java:241)
        - locked <743f6add> (a com.rabbitmq.stream.impl.ConsumersCoordinator$SubscriptionTracker)
        at com.rabbitmq.stream.impl.ConsumersCoordinator$$Lambda$2497/0x0000000101294840.run(Unknown Source)
        at com.rabbitmq.stream.impl.StreamConsumer.closeFromEnvironment(StreamConsumer.java:131)
        at com.rabbitmq.stream.impl.StreamConsumer.close(StreamConsumer.java:124)
       

   Locked ownable synchronizers:
        - locked <3e2f4300> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"rabbitmq-actors-dispatcher-34" - Thread t@90
   java.lang.Thread.State: BLOCKED
        at com.rabbitmq.stream.impl.ConsumersCoordinator$ClientSubscriptionsManager.isFull(ConsumersCoordinator.java:730)
        - waiting to lock <78cd3cab> (a com.rabbitmq.stream.impl.ConsumersCoordinator$ClientSubscriptionsManager) owned by "oems-securities-akka.rabbitmq-actors-dispatcher-33" t@89
        at com.rabbitmq.stream.impl.ConsumersCoordinator$ManagerPool.add(ConsumersCoordinator.java:315)
        - locked <1db2727e> (a com.rabbitmq.stream.impl.ConsumersCoordinator$ManagerPool)
        at com.rabbitmq.stream.impl.ConsumersCoordinator$ManagerPool.access$100(ConsumersCoordinator.java:293)
        at com.rabbitmq.stream.impl.ConsumersCoordinator.subscribe(ConsumersCoordinator.java:113)
        at com.rabbitmq.stream.impl.StreamEnvironment.registerConsumer(StreamEnvironment.java:471)
        at com.rabbitmq.stream.impl.StreamConsumer.<init>(StreamConsumer.java:91)
        at com.rabbitmq.stream.impl.StreamConsumerBuilder.build(StreamConsumerBuilder.java:127)
```

Let me know if you need more details

**Comment by lukebakken** [comment]
> Let me know if you need more details

It would be appreciated to know the following:
* RabbitMQ version
* Erlang version
* OS and version
* Complete code to reproduce the issue. This enables us to spend time diagnosing the issue rather than figuring out exactly what you're doing to trigger it.

**Comment by cporte** [comment]
RabbitMQ version 3.9.8, I'm using the docker image rabbitmq:3.9.8-management (no idea what is the Erland version in it but it shouldn't be relevant to this issue which is really java library related, from the look of it there are a bit too many `synchronized` keywords at the method levels in global objects)
OS is Ubuntu 18.10

I'll try to put up a little project to reproduce sometime this week, it shouldn't be too complicated. The issue really appears almost systematically when a new Consumer is built in one thread when a different thread is busy closing a different Consumer

**Comment by acogoluegnes** [comment]
I managed to reproduce the deadlock, no need to provide more information, thanks. I'm working on a fix.
