### ISSUE TITLE
com.rabbitmq.stream.StreamException: Subscription to stream <stream> failed with code 3 (SUBSCRIPTION_ID_ALREADY_EXISTS)

### ISSUE THREAD

**Issue by earandap** [rabbitmq/rabbitmq-stream-java-client#71]
Hi folks,

I am using rabbitmq-stream to send messages to the WebSocket subscriptions sometimes I am getting this exception: 

```
com.rabbitmq.stream.StreamException: Subscription to stream <stream> failed with code 3 (SUBSCRIPTION_ID_ALREADY_EXISTS)
	at c.r.s.i.ConsumersCoordinator$ClientSubscriptionsManager.add(ConsumersCoordinator.java:679)
	at c.r.s.i.ConsumersCoordinator$ManagerPool.add(ConsumersCoordinator.java:316)
	at c.r.s.i.ConsumersCoordinator$ManagerPool.access$100(ConsumersCoordinator.java:293)
	at c.r.s.impl.ConsumersCoordinator.subscribe(ConsumersCoordinator.java:113)
	at c.r.stream.impl.StreamEnvironment.registerConsumer(StreamEnvironment.java:471)
	at c.r.stream.impl.StreamConsumer.<init>(StreamConsumer.java:91)
	at c.r.s.impl.StreamConsumerBuilder.build(StreamConsumerBuilder.java:127)
	at o.s.r.s.l.StreamListenerContainer.start(StreamListenerContainer.java:172)
```

Can you help me to understand what is the root cause?

RabbitMQ: 3.9.11
Erlang: 24.2
OS and version: Docker, image:  eclipse-temurin:11-jre-focal
I am using Spring WebFlux.

**Comment by acogoluegnes** [comment]
Each consumer has a subscription ID scoped to its connection. The exception say the client tries to register a consumer with an already existing subscription ID. This is likely a bug in the way subscription IDs are allocated on the client side.

Can you provide more information about the use case (setup, application code)? Is the consumer churn high?

A sample project to reproduce would be great.

**Comment by acogoluegnes** [comment]
I could not reproduce with a multi-threaded consumer create/close test. Could you provide a sample project to reproduce or at least illustrate your use case?

**Comment by acogoluegnes** [comment]
Closing because of inactivity.
